# Generated by Django 2.2.1 on 2019-05-26 03:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Datalogger',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_name', models.CharField(max_length=64)),
                ('description', models.CharField(max_length=64)),
                ('temperature_sensor_count', models.SmallIntegerField()),
                ('humidity_sensor_count', models.SmallIntegerField()),
                ('up_since', models.DateTimeField(verbose_name='uninterrupted since')),
                ('last_transmission', models.DateTimeField(verbose_name='last transmission received')),
            ],
        ),
        migrations.CreateModel(
            name='Sensor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=64)),
                ('datalogger', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pulogger.Datalogger')),
            ],
        ),
        migrations.CreateModel(
            name='SensorModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=16)),
                ('description', models.CharField(max_length=64)),
                ('has_temperature', models.BooleanField()),
                ('has_humidity', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='TemperatureDatum',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submission_ip', models.GenericIPAddressField()),
                ('timestamp', models.DateTimeField()),
                ('temperature', models.DecimalField(decimal_places=2, max_digits=4)),
                ('sensor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pulogger.Sensor')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='sensor',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pulogger.SensorModel'),
        ),
        migrations.CreateModel(
            name='HumidityDatum',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submission_ip', models.GenericIPAddressField()),
                ('timestamp', models.DateTimeField()),
                ('humidity', models.DecimalField(decimal_places=2, max_digits=4)),
                ('sensor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pulogger.Sensor')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
