# Generated by Django 2.2.1 on 2019-05-26 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pulogger', '0002_auto_20190525_2058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datalogger',
            name='last_transmission',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last transmission received'),
        ),
        migrations.AlterField(
            model_name='datalogger',
            name='up_since',
            field=models.DateTimeField(blank=True, null=True, verbose_name='uninterrupted since'),
        ),
    ]
