# Generated by Django 2.2.1 on 2019-05-26 19:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pulogger', '0003_auto_20190525_2101'),
    ]

    operations = [
        migrations.CreateModel(
            name='DatumTypes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=16)),
            ],
        ),
        migrations.CreateModel(
            name='SensorDatum',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submission_ip', models.GenericIPAddressField()),
                ('timestamp', models.DateTimeField()),
                ('value', models.DecimalField(decimal_places=2, max_digits=4)),
            ],
        ),
        migrations.CreateModel(
            name='SensorModelDatumType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datum_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pulogger.DatumTypes')),
            ],
        ),
        migrations.RemoveField(
            model_name='temperaturedatum',
            name='sensor',
        ),
        migrations.RemoveField(
            model_name='sensormodel',
            name='has_humidity',
        ),
        migrations.RemoveField(
            model_name='sensormodel',
            name='has_temperature',
        ),
        migrations.AddField(
            model_name='datalogger',
            name='passcode',
            field=models.CharField(default='123456', max_length=6),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sensor',
            name='sensor_name',
            field=models.CharField(default='placeholderName', max_length=16),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='HumidityDatum',
        ),
        migrations.DeleteModel(
            name='TemperatureDatum',
        ),
        migrations.AddField(
            model_name='sensormodeldatumtype',
            name='sensor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pulogger.SensorModel'),
        ),
        migrations.AddField(
            model_name='sensordatum',
            name='sensor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pulogger.Sensor'),
        ),
        migrations.AddField(
            model_name='sensordatum',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pulogger.DatumTypes'),
        ),
    ]
