# Generated by Django 2.2.1 on 2019-05-26 21:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pulogger', '0004_auto_20190526_1200'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DatumTypes',
            new_name='DatumType',
        ),
    ]
